- name: Hello World Sample - Miku
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: fact beallitas 
      set_fact:
        my_rows: >-
          {{ csv_content | community.general.from_csv(
               fieldnames: ['vcenter_host', 'esx_hostname', 'template_name', 'dns', 'suffix',
                        'vmname', 'disksize', 'memory', 'vcpu', 'ds', 'folder', 'vlan',
                        'ip', 'netmask', 'gwi'],
               delimiter: ';') }}
    - name: print
      debug:
        msg: " Ez lett: {{ my_rows }}"
