- name: Hello World Sample - Miku
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
          #    - name: CSV Ferinek
          #      community.general.read_csv:
        #        path: "{{ csv_content }}"
          #        fieldnames: vcenter_host,esx_hostname,template_name,dns,suffix,vmname,disksize,memory,vcpu,ds,folder,vlan,ip,netmask,gw,
          #        delimiter: ";"
          #      register: srv_list
          #    - name: CSV string feldolgozása listává
          #      set_fact:
          #        my_rows: "{{ csv_content | community.general.from_csv(fieldnames='vcenter_host,esx_hostname,template_name,dns,suffix,vmname,disksize,memory,vcpu,ds,folder,vlan,ip,netmask,gwi',delimiter=';') }}"
    - name: fact beallitas 
      set_fact:
        my_rows: >-
          {{ csv_content | community.general.from_csv(
               fieldnames: ['vcenter_host', 'esx_hostname', 'template_name', 'dns', 'suffix',
                        'vmname', 'disksize', 'memory', 'vcpu', 'ds', 'folder', 'vlan',
                        'ip', 'netmask', 'gwi'],
               delimiter: ';'
         ) }}

    - name: print
      debug:
        msg: " Ez lett: {{ my_rows }}"
