---
- name: Ki írta ki ezt a playbookot?
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - set_fact:
        launched_by: "{{ tower_user_name | trim }}"
        launched_by_with_a: "{{ (tower_user_name | trim) + '-a' }}"
        launched_id: "{{ tower_job_id | trim }}"
        launched_type: "{{ tower_job_launch_type | trim }}"

    - name: Ki indította a template-et? 
      debug:
        msg: "Ez lett az admin users: {{ launched_by_with_a }} Ezzel a userrel inditotta:{{ launched_by }} Tipusa: {{ launched_type }} és az ID: {{ launched_id }}"
